== Firewall

  yum install lokkit

  lokkit --port 8181:tcp
  lokkit --port 22:tcp
  
  lokkit --enabled
  lokkit --update

OR

  firewall-cmd --add-service=ssh
  
  iptables --list
  Chain INPUT (policy ACCEPT)
  target     prot opt source               destination
  RH-Firewall-1-INPUT  all  --  anywhere             anywhere

  Chain FORWARD (policy ACCEPT)
  target     prot opt source               destination
  REJECT     all  --  anywhere             anywhere            reject-with icmp-host-prohibited

  Chain OUTPUT (policy ACCEPT)
  target     prot opt source               destination

  Chain RH-Firewall-1-INPUT (1 references)
  target     prot opt source               destination
  ACCEPT     all  --  anywhere             anywhere
  ACCEPT     icmp --  anywhere             anywhere            icmp any
  ACCEPT     esp  --  anywhere             anywhere
  ACCEPT     ah   --  anywhere             anywhere
  ACCEPT     udp  --  anywhere             224.0.0.251         udp dpt:mdns
  ACCEPT     udp  --  anywhere             anywhere            udp dpt:ipp
  ACCEPT     tcp  --  anywhere             anywhere            tcp dpt:ipp
  ACCEPT     all  --  anywhere             anywhere            state RELATED,ESTABLISHED
  ACCEPT     tcp  --  anywhere             anywhere            state NEW tcp dpt:8181
  ACCEPT     tcp  --  anywhere             anywhere            state NEW tcp dpt:ssh
  REJECT     all  --  anywhere             anywhere            reject-with icmp-host-prohibited

== SSH

  service sshd start
  chkconfig sshd on


== Locale issue with Fedora 8

http://serverfault.com/questions/320971/centos-6-and-locale-error

Add

  LC_CTYPE="en_US.UTF-8"
  to /etc/sysconfig/i18n.

== Configure VirtualBox 4.3.6

http://www.if-not-true-then-false.com/2010/install-virtualbox-with-yum-on-fedora-centos-red-hat-rhel/
http://www.if-not-true-then-false.com/2010/install-virtualbox-guest-additions-on-fedora-centos-red-hat-rhel/

. Change to root User

  su -

. Install Fedora or RHEL Repo Files
  
  cd /etc/yum.repos.d/
  wget http://download.virtualbox.org/virtualbox/rpm/fedora/virtualbox.repo

. Update latest packages and check your kernel version

Update packages
 
  yum update

Check that that you are running latest installed kernel version
Output of following commands version numbers should match:

  rpm -qa kernel |sort -V |tail -n 1
 
  uname -r

. Restart

  reboot

. Install following dependency packages

  Not sure if the following command is required by Fedora 20

  ## CentOS 6 and RHEL 6 ##
  rpm -Uvh http://dl.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm

  yum install binutils gcc make patch libgomp glibc-headers glibc-devel kernel-headers kernel-devel dkms
 
  ## PAE kernel users install ##
  # yum install binutils gcc make patch libgomp glibc-headers glibc-devel kernel-headers kernel-PAE-devel dkms

== Install VirtualBox

  yum install VirtualBox-4.3

Note:
This command create automatically vboxusers group and VirtualBox user must be member of that group.
This command also build needed kernel modules.
Rebuild kernel modules with following command:

  /etc/init.d/vboxdrv setup
  ## OR ##
  service vboxdrv setup

 . Add VirtualBox User(s) to vboxusers Group

Replace user_name with your own user name or some another real user name.
  
  usermod -a -G vboxusers dabou

  VirtualBox

Troubleshooting

If you have problems with KERN_DIR parameter or your kernel directory is not automatically detected then set KERN_DIR environment variable manually, using following method:
## Current running kernel on Fedora ##
KERN_DIR=/usr/src/kernels/`uname -r`
 
## Current running kernel on CentOS and Red Hat (RHEL) ##
KERN_DIR=/usr/src/kernels/`uname -r`-`uname -m`
 
## Fedora example ##
KERN_DIR=/usr/src/kernels/2.6.33.5-124.fc13.i686
 
## CentOS and Red Hat (RHEL) example ##
KERN_DIR=/usr/src/kernels/2.6.18-194.11.1.el5-x86_64
 
## Export KERN_DIR ##
export KERN_DIR

== Fedy Tool

  su -c "curl https://satya164.github.io/fedy/fedy-installer -o fedy-installer && chmod +x fedy-installer && ./fedy-installer"

== NetAtalk / Avahi

http://blog.lowsnr.net/2013/09/07/accessing-a-fedora-19-fileserver-from-mac-os-x/
http://jeandoyon.wordpress.com/2010/03/31/sharing-files-between-osx-and-fedora-12/
http://devel.datif.be/howto/serve-files-using-afp-with-netatalk-from-fedora-linux-to-mac-osx-leopard-clients/

== Samba

As netatalk does not seem to work on Fedora 20, we will use SAMBA

https://ask.fedoraproject.org/en/question/40353/how-to-enable-samba-share-for-a-specific-directory-fedora-20/

Additional steps :

- Added on fedora machine a username 

    smbpasswd -a USERNAME

- The USERNAME is used to define which user can connect using SMB client (from MacOs, ...)

== Backup

1) Rsync

The following publications describe solutions to sync or rsync files of the disk to a 
backup drive but don't create an image of the disk

http://blog.interlinked.org/tutorials/rsync_time_machine.html
http://wiki.vps.net/vps-net-features/cloud-servers/miscellaneous/rsync-backuprestore-instructions/

https://wiki.archlinux.org/index.php/Full_system_backup_with_rsync
http://www.tecmint.com/rsnapshot-a-file-system-backup-utility-for-linux/

http://www.rsnapshot.org/howto/1.2/rsnapshot-HOWTO.en.html

2) Image backup

With the help of clonezilla, we can using a USB key boot clonezilla (= linux os) and backup an entire drive to an external disk or restore it.

The USB key can be created using the latest stable clonezilla distribution available link:here[http://clonezilla.org/downloads/download.php?branch=stable]. When the file has been downloaded, right click on the file (in Fedora) and select 'Disk image writer', then a popup window will be displayed, select the USB driver (/dev/sdb) and click on the button 'Start restoring'. When the process is done, reboot with the key

Remark : The USB key should be formated with FAT format (could be done on fedora).

http://www.dedoimedo.com/computers/clonezilla.html

== Hardware info 

http://www.binarytides.com/linux-commands-hardware-info/

== Limit number of kernels and delete some

http://www.if-not-true-then-false.com/2012/delete-remove-old-kernels-on-fedora-centos-red-hat-rhel/

  rpm -q kernel
  package-cleanup --oldkernels --count=2
  
To make this change permanent

  Edit /etc/yum.conf and set installonly_limit:
  installonly_limit=2
  
== Google Chrome Remote Desktop

Initial documentation used to create rpm from deb package : http://sprackle.org/2014/07/how-to-get-chrome-remote-desktop-beta-working-under-fedora/

1) Alien tool must installed

  sudo yum install alien
  
2) Download Google Chrome package

  https://support.google.com/chrome/answer/1649523?hl=en
   
3) Generate rpm

  alien -r chrome-remote-desktop_current_amd64.deb
  
4) Add missing packages

  yum install python-psutil xorg-x11-server-Xvfb
  
5) Create group

  groupadd chrome-remote-desktop
  usermod -G chrome-remote-desktop dabou
  chkconfig chrome-remote-desktop on
  
6) Force RPM

  rpm -Uvh --force chrome-remote-desktop-35.0.1916.17-2.x86_64.rpm
  
   


  


